USE [master]
GO

/****** Object:  Database [yaguarete]    Script Date: 5/9/2021 11:29:11 ******/
CREATE DATABASE [yaguarete]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'yaguarete', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER02\MSSQL\DATA\yaguarete.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'yaguarete_log', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER02\MSSQL\DATA\yaguarete_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [yaguarete].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [yaguarete] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [yaguarete] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [yaguarete] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [yaguarete] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [yaguarete] SET ARITHABORT OFF 
GO

ALTER DATABASE [yaguarete] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [yaguarete] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [yaguarete] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [yaguarete] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [yaguarete] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [yaguarete] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [yaguarete] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [yaguarete] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [yaguarete] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [yaguarete] SET  DISABLE_BROKER 
GO

ALTER DATABASE [yaguarete] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [yaguarete] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [yaguarete] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [yaguarete] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [yaguarete] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [yaguarete] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [yaguarete] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [yaguarete] SET RECOVERY FULL 
GO

ALTER DATABASE [yaguarete] SET  MULTI_USER 
GO

ALTER DATABASE [yaguarete] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [yaguarete] SET DB_CHAINING OFF 
GO

ALTER DATABASE [yaguarete] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [yaguarete] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [yaguarete] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [yaguarete] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [yaguarete] SET QUERY_STORE = OFF
GO

ALTER DATABASE [yaguarete] SET  READ_WRITE 
GO

